### ISSUE TITLE
Make Contributors Guideline

### ISSUE THREAD

**Issue by KamalDGRT** [DSC-SIST/Event-Aggregator#1]
### AIM

Create Contributors Guideline to help new Contributors get started with this Project.

#### Features

- Add a `CONTRIBUTING.md` to allow new users to get started with knowing how to contribute.
- Add Screenshots wherever possible.
- Mention the way to set the project locally in the PC
- Add the basic information about creating Issues, Pull Requests and Branching.
- Mention tutorials related to Git and GitHub to help them better understand.

**Comment by javeed3157** [comment]
I would like to work on this issue.
