### ISSUE TITLE
[Feature] Setup Welcome Bot + Stale Bot for Contributors

### ISSUE THREAD

**Issue by KamalDGRT** [DSC-SIST/Event-Aggregator#10]
### Objective :pushpin:

- To automate the greeting message while creating issues.
- To add the label as `stale` if the issue/pr is inactive

### Features to be added / modified :ballot_box_with_check:

This Issue requires two things:

- Add a GitHub Action to mark stale Issues with a Tag. Issues that are not assigned, or has not been mentioned anywhere for more than 7 Days should be tagged with a `Stale` tag automatically.

- Add a GitHub Action that can welcome new contributors.

**Comment by deeptea22** [comment]
I would like to work on this issue.

**Comment by KamalDGRT** [comment]
Good work @deeptea22 :tada:
