### ISSUE TITLE
Instructions for Setting up the Project

### ISSUE THREAD

**Issue by KamalDGRT** [DSC-SIST/Event-Aggregator#2]
### AIM

List out the instructions for setting up the project to help new Contributors get started with this Project.

#### Features

- Add a `Setup.md` to allow new users to get started with knowing how to execute and see the output.
- Add Screenshots wherever possible.
- Mention the tools that are to be used while setting up the project
- Include the links to setting up the same from [here](https://github.com/KamalDGRT/SetupStuff)
- Add instructions to virtual hosting the project

**Comment by kanika-08** [comment]
I would like to work on this issue.
